apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomicred
  namespace: atomic-red
  labels:
    app: atomicred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomicred
  template:
    metadata:
      labels:
        app: atomicred
    spec:
      containers:
        - name: atomicred
          image: redcanary/invoke-atomicredteam
          imagePullPolicy: "IfNotPresent"
          command: ["sleep", "3560d"]
          securityContext:
            privileged: true
      nodeSelector:
        kubernetes.io/os: linux
